language: java
jdk:
  - oraclejdk8
addons:
  sauce_connect: true
before_install:
  - nvm install 5
  - npm install -g lerna@2.0.0-beta.30
  - lerna bootstrap
install:
  - npm i
script: travis_wait gulp test:saucelabs
